title: Digital Media by Chris Violette
author:
  name: Chris Violette
metadata:
    description: 'A Maine-based web developer, designer, and photographer.'

# Header customization
header:
  title: Hi, I'm Chris.
  description: I'm a Maine based <span>web developer</span>, <span>designer</span> and <span>photographer</span><br><a class="smoothscroll" href="#portfolio">Let's get creative</a>.
  scrolldown: portfolio
copyright:
    - line: &copy; Copyright 2017 Chris Violette
social:
- url: "https://twitter.com/pixleight/"
  icon: twitter
- url: "https://github.com/pixleight"
  icon: github
- url: "https://www.linkedin.com/in/chris-violette-3472a8b/"
  icon: linkedin
- url: "https://www.instagram.com/pixleight/"
  icon: instagram
- url: "https://500px.com/pixleight"
  icon: 500px


# HOW TO CREATE A VALID ID TO USE:
# Go to www.twitter.com and sign in as normal, go to your settings page.
# Go to "Widgets" on the left hand side.
# Create a new widget for what you need eg "user time line" or "search" etc.
# Feel free to check "exclude replies" if you don't want replies in results.
# Now go back to settings page, and then go back to widgets page and
# you should see the widget you just created. Click edit.
# Look at the URL in your web browser, you will see a long number like this:
# 657554810648948736
# Use this as your ID below instead!

twitter:
